staging-settings:
  user-workflow:
    workflow-name: "trende-cre-workflow-staging"
  workflow-artifacts:
    workflow-path: "./main.ts"
    config-path: "./config.json"
    secrets-path: "./secrets.yaml"
  rpc-urls:
    ethereum-testnet-sepolia-arbitrum-1: "https://sepolia-rollup.arbitrum.io/rpc"
